const producList = [
  {
    id: 1,
    image: "./img/chair1-1.jpg",
    sale: false,
    name: "Black Chair",
    price: "299.00",
  },
  {
    id: 2,
    image: "./img/table1.jpg",
    sale: false,
    name: "Black Table",
    price: "299.00",
  },
  {
    id: 3,
    image: "./img/cupblue.jpg",
    sale: false,
    name: "Blue Cup",
    price: "28.00",
  },

  {
    id: 4,
    image: "./img/box1.jpg",
    sale: false,
    name: "Brown Box",
    price: "29.00",
  },
  {
    id: 5,
    image: "./img/cup2.jpg",
    sale: false,
    name: "BW Coffee Cups",
    price: "29.00",
  },

  {
    id: 6,
    image: "./img/cup3.jpg",
    sale: false,
    name: "Coffee Cup",
    price: "19.00",
  },
  {
    id: 7,
    image: "./img/lamp1.jpg",
    sale: false,
    name: "Creative Lamps",
    price: "99.00",
  },
  {
    id: 8,
    image: "./img/bag2.jpg",
    sale: false,
    name: "Modern Bag",
    price: "129.00",
  },
  {
    id: 9,
    image: "./img/bench1.jpg",
    sale: false,
    name: "Modern Bench",
    price: "135.00",
  },
  {
    id: 10,
    image: "./img/glass1.jpg",
    sale: true,
    price_pre: "19.00",
    name: "Modern Glass",
    price: "15.00",
  },
  {
    id: 11,
    image: "./img/table3.jpg",
    sale: false,
    name: "Coffee Table",
    price: "79.00",
  },
  {
    id: 13,
    image: "./img/chair2.jpg",
    sale: true,
    price_pre: "399.00",
    name: "Neue Chair",
    price: "289.00",
  },
  {
    id: 12,
    image: "./img/tshirt.jpg",
    sale: false,
    name: "Modern Tshirt",
    price: "9.00",
  },
  {
    id: 14,
    image: "./img/glasses.jpg",
    sale: false,
    name: "Sunglasses",
    price: "199.00",
  },
  {
    id: 15,
    image: "./img/lamp2.jpg",
    sale: false,
    name: "Table Lamp",
    price: "79.00",
  },
  {
    id: 16,
    image: "./img/watch.jpg",
    sale: false,
    name: "Tisso Watch",
    price: "289.00",
  },
  {
    id: 17,
    image: "./img/lamp3.jpg",
    sale: true,
    price_pre: "100.000",
    name: "Wood Lamp",
    price: "89.00",
  },
  {
    id: 18,
    image: "./img/table2.jpg",
    name: "Wood Table",
    price: "79.00",
  },
];
export { producList };
